### ISSUE TITLE
[BUG] Website is broken because of rate-limiting

### ISSUE THREAD

**Issue by nsde** [FoxGPT/gpt#6]
The website breaks because when someone visits the website, a lot of requests are being made.

I think caching might solve this, but I'm not entirely sure.
You should also think about using Cloudflare for rate-limiting instead.
Moreover, I think you should separate the rate limits for the website from the ones of the API.

Thanks!

![image](https://github.com/FoxGPT/gpt/assets/67185896/89e32b3a-9b98-42d2-8161-b80be7e2ebf1)

**Comment by yinm0591** [comment]
I think it should be caused by this reason:  https://github.com/FoxGPT/gpt/issues/5
